### ISSUE TITLE
Error printed when building from ps1

### ISSUE THREAD

**Issue by AArnott** [clcrutch/DotNetMDDocs#2]
On a clean clone, running `.\build.ps1` produced this output:

```ps1
PS D:\git\DotNetMDDocs> .\build.ps1
Preparing to run build script...
Test-Path : Illegal characters in path.
At D:\git\DotNetMDDocs\build.ps1:129 char:97
+ ... string]::IsNullOrEmpty($_)) -and (Test-Path $_ -PathType Container) }
+                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Test-Path], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.TestPathCommand

Running build script...
```

It went on to apparently succeed in build, but the error it printed along the way raises doubts.

**Comment by clcrutch** [comment]
This script is pulled directly from the [Cake Build](https://github.com/cake-build/resources), so I'm not super familiar with the script.  That being said, the line in question looks like this:
```powershell
$existingPaths = $Env:Path -Split ';' | Where-Object { (![string]::IsNullOrEmpty($_)) -and (Test-Path $_ -PathType Container) }
```
So I'd be interested in knowing if the your `path` environment variable somehow has some malformed paths in it that Windows is otherwise ignoring.

A quick check would be to execute this:
```powershell
$Env:Path -Split ';' | Where-Object { $a = $_; $null -ne ([System.IO.Path]::InvalidPathChars | Where-Object { $a.Contains($_) }) }
```

**Comment by AArnott** [comment]
Yup. I had a PATH entry that ended with `"`. Sorry for the noise. Thanks for the tip on finding it.
